version: "3.9"
services:
    oracle:
        image: 'store/oracle/database-enterprise:12.2.0.1'
        container_name: oracle
        ports:
        - "1521:1521"
        volumes:
        - ./scripts:/scripts
    goldengate:
        image: maurizio/goldengate-standard:latest
